# Import libraries

In [1]:
import os
import pandas as pd
import numpy as np

# Import data

In [2]:
os.listdir('../Nkhoma_data')

['Inpatient list Surgery',
 'Poor Patient Funds',
 'Data',
 'Volunteer Agreement',
 'ICU_research.xlsx',
 'laparoscopy_analysed.xlsx']

In [3]:
df = pd.read_excel("../Nkhoma_data/ICU_research.xlsx")

In [4]:
df

,Unnamed: 0,Year of Birth,Gender,Hospital Admission Date,Hospital Discharge Date,Date of Surgery,Type of Surgery,ICU Admission Date,ICU Discharge Date,Intubation,...,Disability at discharge,Cause of Death,Discharge to,qSOFA,Length of ICU stay (nights),Intubation (nights),Hospital Stay (nights),Discharge after ICU (nights),Age (years),Comment
0,1.0,1944.0,M,2023-07-24 00:00:00,2023-07-27 00:00:00,2023-07-26 00:00:00,Hemithyroidectomy,2023-07-25,2023-07-26,Yes pre ICU,...,Potential of full recovery,NaN,Ward,NaN,1.0,0.0,3.0,1.0,79.0,NaN
1,2.0,1988.0,M,2023-07-14 00:00:00,2023-08-21 00:00:00,2023-08-17 00:00:00,Buccal graft urethroplasty,2023-08-17,2023-08-20,Yes pre ICU,...,Potential of full recovery,NaN,Ward,NaN,3.0,1.0,38.0,1.0,35.0,NaN
2,3.0,1977.0,F,2023-08-12 00:00:00,2023-08-18 00:00:00,NaN,EGD,2023-08-17,2023-08-18,No,...,Death,Possible Cryptococcal Meningitis,Death,3.0,1.0,0.0,6.0,0.0,46.0,NaN
3,4.0,2010.0,F,2023-07-31 00:00:00,2023-08-08 00:00:00,2023-07-31 00:00:00,Chest Tube Placement,2023-07-31,2023-08-05,No,...,Potential of full recovery,NaN,Ward,NaN,5.0,0.0,8.0,3.0,13.0,NaN
4,5.0,1972.0,M,2023-08-10 00:00:00,2023-08-12 00:00:00,2023-08-10 00:00:00,EGD and Banding,2023-08-10,2023-08-11,No,...,Potential of full recovery,NaN,Ward,NaN,1.0,0.0,2.0,1.0,51.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
346,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
347,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
348,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
349,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,...,NaN,NaN,NaN,NaN,296.0,NaN,NaN,NaN,NaN,NaN

In [5]:
surgery_map = {
    # === Caesarean Section ===
    'C/S': 'Caesarean Section',
    'c/section': 'Caesarean Section',
    'Caesarian Section': 'Caesarean Section',
    'Ceasarian section': 'Caesarean Section',
    'cessarian section': 'Caesarean Section',

    # === EGD ===
    ' EGD and Banding': 'EGD',
    'EGD and Banding': 'EGD',
    
    'EGD and clipping, then exp lap with oversew of gastric ulcer': 'EGD',
    'EGD glueing ': 'EGD',
    'EGD glueing': 'EGD',

    'Endoscopy, Banding': 'EGD',
    'endoscopy, Banding': 'EGD',
    'Banding': 'EGD',
    'banding': 'EGD',
    # === Cholecystectomy ===
    'laparoscopic Cholecystectomy': 'Laparoscopic Cholecystectomy',
    

    # === Open Prostatectomy ===
    'open prostatectomy': 'Open Prostatectomy',
    'Open prostectomy': 'Open Prostatectomy',
    'Prostate??': 'Open Prostatectomy',
    'Open Prostatectomy and Take back': 'Open Prostatectomy',
    'Open Prostatectomy and 2 Take backs': 'Open Prostatectomy',

    # === Hysterectomy ===
    ' TAH': 'Hysterectomy',
    'TAH': 'Hysterectomy',
    'TAH and BSO': 'Hysterectomy',
    'TAH, J-stent ureteral Injury Repair': 'Hysterectomy',
    'TAH,BSO and Underlay Incisional hernia repair': 'Hysterectomy',
    'Subtotal Hysterectomy': 'Hysterectomy',
    'subtotal Hysterectomy + bladder repair': 'Hysterectomy',

    # === Debridement ===
    'chest Debridement': 'Debridement',
    'Cervial/chest Debridement, SSG': 'Debridement',
    'Extensive Debridement with I&D': 'Debridement',
    'Scrotal/perianal Debribement': 'Debridement',

    # === Exploratory Laparotomy (plain) ===
    'Ex Lap': 'Exploratory Laparotomy',
    'Ex lap': 'Exploratory Laparotomy',
    'ex lap': 'Exploratory Laparotomy',
    'Ex laparatomy': 'Exploratory Laparotomy',
    'ex-laparatomy': 'Exploratory Laparotomy',
    'Exp laparatomy': 'Exploratory Laparotomy',
    'Exploratory laparatomy': 'Exploratory Laparotomy',
    'Exploratory laparotomy, washout, drain placement': 'Exploratory Laparotomy',
    'exploration': 'Exploratory Laparotomy',
    'EX-lap, Adhesiolysis': 'Exploratory Laparotomy',
    'Exp-laparotomy, re-lap 10/11/2024': 'Exploratory Laparotomy',
    'Exploratory Laparatomy, modified Grahams patch': 'Exploratory Laparotomy',
    'exploratory laparatomy, liver packing, then 27/8 relap': 'Exploratory Laparotomy',
    'Expl laparotomy, lavage, repair and patch of gastric perf': 'Exploratory Laparotomy',
    'Ex-lap, Washout': 'Exploratory Laparotomy',
    'Ex-lap, bowel decompression': 'Exploratory Laparotomy',
    'Ex lap, Psoas Abscess drainage/Appendectomy': 'Exploratory Laparotomy',
    'ex-lap,rectal sigmoid resection': 'Exploratory Laparotomy',
    "Modified Graham's Patch": 'Exploratory Laparotomy',
    'Abdominal wshout and closure': 'Exploratory Laparotomy',
    'Second look, Waschout': 'Exploratory Laparotomy',

    # === Laparotomy with Bowel Resection ===
    'Damage Control ileo-resection and washout': 'Exploratory Laparotomy with Bowel Resection',
    'damage control ileo-resection and washout/ Bowel anastomosis': 'Exploratory Laparotomy with Bowel Resection',
    'Exploratorory Laparotomy: Adhensions plus bowel resection': 'Exploratory Laparotomy with Bowel Resection',
    'Exploratory laparotomy, ileoal resection, ': 'Exploratory Laparotomy with Bowel Resection',
    'Ex lap, Ileal transverse side to end anastomosis': 'Exploratory Laparotomy with Bowel Resection',
    'Ex lap, Right hemicolectomy': 'Exploratory Laparotomy with Bowel Resection',
    'Diagnostic laparoscopy, adhesiolysis, Konversion to ope right Hemicolectomy, E-E Ileotransversotomy': 'Exploratory Laparotomy with Bowel Resection',
    'Small bowel resection, anastomosis': 'Exploratory Laparotomy with Bowel Resection',
    'Sigmoid resection': 'Exploratory Laparotomy with Bowel Resection',
    'Right hemicolectomy, duodenum wedge resection, gastrojejunostomy': 'Exploratory Laparotomy with Bowel Resection',
    'Eviceration of small bowel': 'Exploratory Laparotomy with Bowel Resection',
    'Ex Lap, Ileal transverse side to end anastomosis': 'Exploratory Laparotomy with Bowel Resection',
    'Exploratory laparotomy, ileoal resection,':'Exploratory Laparotomy with Bowel Resection',
        # === Exploratory Laparotomy with Stoma ===
    'Exlap, ileostomy': 'Exploratory Laparotomy with Bowel Resection',
    'ex lap, ileostomy': 'Exploratory Laparotomy with Bowel Resection',
    
    # === Exploratory Laparotomy with Splenectomy ===
    'Exploratory laparotomy, Splenectomy': 'Exploratory Laparotomy with Splenectomy',
    'Splenectomy': 'Exploratory Laparotomy with Splenectomy',
    'spleenectomy': 'Exploratory Laparotomy with Splenectomy',

    # === No Surgery ===
    'No Surgery': 'No Surgery',
    'No surgery': 'No Surgery',
    'No surgery (Poison)': 'No Surgery',
    'No surgery( Pleural and ascitic tap)': 'No Surgery',
    'asthma': 'No Surgery',

    # === Misc ===
    'Flexible Sigmoidoscopy/ Reopenning': 'Other',
    'Right Chest Tube Placement': 'Chest Tube Placement',
    'Rib resection, irrigation, skin flap over diaphragm, packing': 'Other',

    # == Total/Hemi thyroidectomy == #
    'Hemithyroidectomy':'Hemi/Total Thyroidectomy',
    'total thyroidectomy':'Hemi/Total Thyroidectomy',
    'Left Hemithyroidectomy and Isthmussectomy':'Hemi/Total Thyroidectomy',
    # == Other == #
    'Bladder mass excision': 'Other',
    'Buccal graft urethroplasty': 'Other',
    'Rib Resection': 'Other',
    'Bilateral Inguinal Hernia Repair': 'Other',
    'Open Cholecystectomy & specimen': 'Other',
}
df['Type of Surgery Cleaned'] = df['Type of Surgery'].str.strip().replace(surgery_map)

In [6]:
sorted(df['Type of Surgery Cleaned'].dropna().unique())

['Caesarean Section',
 'Chest Tube Placement',
 'Debridement',
 'EGD',
 'Exploratory Laparotomy',
 'Exploratory Laparotomy with Bowel Resection',
 'Exploratory Laparotomy with Splenectomy',
 'Exploratory Laparotomy with Stoma',
 'Hemi/Total Thyroidectomy',
 'Hysterectomy',
 'Laparoscopic Cholecystectomy',
 'No Surgery',
 'Open Prostatectomy',
 'Other']

In [7]:
df['Type of Surgery Cleaned'].value_counts()

Type of Surgery Cleaned
No Surgery                                     42
Exploratory Laparotomy                         27
Exploratory Laparotomy with Bowel Resection    12
EGD                                             9
Caesarean Section                               8
Other                                           7
Open Prostatectomy                              6
Hysterectomy                                    6
Debridement                                     5
Hemi/Total Thyroidectomy                        3
Chest Tube Placement                            3
Exploratory Laparotomy with Splenectomy         3
Laparoscopic Cholecystectomy                    2
Exploratory Laparotomy with Stoma               2
Name: count, dtype: int64

In [10]:
df[['Type of Surgery Cleaned']]

      Type of Surgery Cleaned
0    Hemi/Total Thyroidectomy
1                       Other
2                         EGD
3        Chest Tube Placement
4                         EGD
..                        ...
345                       NaN
346                       NaN
347                       NaN
348                       NaN
349                       NaN

[350 rows x 1 columns]